# Generated by Django 3.1.1 on 2020-10-06 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_auto_20200923_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='Seasons',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='Actors',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='media',
            name='Awards',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='media',
            name='BoxOffice',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='media',
            name='Country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='media',
            name='DVD',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='Director',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='media',
            name='Genre',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='media',
            name='Language',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='media',
            name='Metascore',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='Plot',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='media',
            name='Production',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='media',
            name='Rated',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='media',
            name='Released',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='Runtime',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='media',
            name='Title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='media',
            name='Type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='media',
            name='Website',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='media',
            name='Writer',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='media',
            name='imdbID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='media',
            name='imdbRating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='imdbVotes',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
