# Generated by Django 3.1.2 on 2020-12-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default='', max_length=100)),
                ('Password', models.CharField(default='', max_length=100)),
                ('Viewed', models.CharField(default='', max_length=1000)),
                ('PlanToWatch', models.CharField(default='', max_length=1000)),
                ('Dropped', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
