# Generated by Django 3.1.1 on 2021-01-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201228_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Password',
        ),
        migrations.AlterField(
            model_name='user',
            name='Dropped',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='PlanToWatch',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='Viewed',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
