# Generated by Django 3.1.1 on 2020-09-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Year', models.IntegerField()),
                ('Rated', models.CharField(max_length=50)),
                ('Released', models.DateField()),
                ('Runtime', models.CharField(max_length=50)),
                ('Genre', models.CharField(max_length=50)),
                ('Director', models.CharField(max_length=50)),
                ('Writer', models.CharField(max_length=200)),
                ('Actors', models.CharField(max_length=100)),
                ('Plot', models.CharField(max_length=250)),
                ('Language', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=50)),
                ('Awards', models.CharField(max_length=100)),
                ('Poster', models.CharField(max_length=200)),
                ('Metascore', models.IntegerField()),
                ('imdbRating', models.IntegerField()),
                ('imdbVotes', models.IntegerField()),
                ('imdbID', models.CharField(max_length=50)),
                ('Type', models.CharField(max_length=50)),
                ('DVD', models.DateField()),
                ('BoxOffice', models.CharField(max_length=50)),
                ('Production', models.CharField(max_length=50)),
                ('Website', models.CharField(max_length=50)),
            ],
        ),
    ]
